# Definição dos serviços (contêineres)
services:
  # Serviço do Banco de Dados PostgreSQL
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: pma
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  # Serviço do Redis (Para a Fila do BullMQ)
  redis:
    image: redis:alpine
    container_name: redis_queue
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

  # Serviço do MinIO (armazenamento de objetos)
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    volumes:
      - minio_data:/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # Serviço para criar o bucket no MinIO após ele iniciar
  create-bucket:
    image: quay.io/minio/mc:latest
    depends_on:
      - minio
    networks:
      - app_network
    entrypoint: >
      /bin/sh -c "
      set -x;
      /usr/bin/mc alias set myminio http://minio:9000 admin password;
      /usr/bin/mc mb myminio/atos-normativos;
      /usr/bin/mc policy set public myminio/atos-normativos;
      exit 0;
      "

  # ==========================================
  # NOVO: Serviço de Backup Automático Semanal
  # ==========================================
  backup_semanal:
    image: alpine:latest
    container_name: backup_cron
    restart: always
    depends_on:
      - db
    networks:
      - app_network
    volumes:
      - ./backups_semanais:/backups # Cria a pasta de backups no servidor
      - minio_data:/minio_data:ro # Lê a pasta do MinIO com segurança
    environment:
      - PGPASSWORD=senha123
    entrypoint: >
      /bin/sh -c "
      apk add --no-cache postgresql-client tar tzdata &&
      cp /usr/share/zoneinfo/America/Maceio /etc/localtime &&
      cat << 'EOF' > /backup.sh
      #!/bin/sh
      DATA=\$$(date +%Y-%m-%d_%H-%M)
      echo \"Iniciando backup em: \$$DATA\"
      pg_dump -h db -U usuario -d pma > /backups/db_\$$DATA.sql
      tar -czf /backups/minio_\$$DATA.tar.gz -C /minio_data .
      echo \"Backup finalizado com sucesso!\"
      EOF
      chmod +x /backup.sh &&
      echo '0 6 * * 1 /backup.sh' > /etc/crontabs/root &&
      echo 'Executando backup imediato da primeira vez...' &&
      /backup.sh &&
      echo 'Cron iniciado! Próximo backup programado para Segunda-feira às 06:00.' &&
      crond -f -d 8
      "

# Definição dos volumes
volumes:
  postgres_data:
  minio_data:
  redis_data:

# Definição das redes
networks:
  app_network: